statuses = [
    {'code': 'AUTOMATIC_RENEW', 'label': 'Automatic renew'},
    {'code': 'AUTO_WILL_SUPPLY', 'label': 'Automatic will supply'},
    {'code': 'BAD_CITATION', 'label': 'Bad citation'},
    {'code': 'CANCEL_NOT_ACCEPTED', 'label': 'Cancel request not accepted'},
    {'code': 'CANCELLED', 'label': 'Cancelled by partner'},
    {'code': 'CLAIMED', 'label': 'Claimed'},
    {'code': 'CONDITIONAL', 'label': 'Conditional'},
    {'code': 'REQUEST_CREATED_BOR', 'label': 'Created borrowing request'},
    {'code': 'DAMAGED_COMMUNICATED', 'label': 'Damaged communicated'},
    {'code': 'DECLARED_LOST', 'label': 'Declared lost by partner'},
    {'code': 'RECEIVED_DIGITALLY', 'label': 'Digitally received by library'},
    {'code': 'EXPIRED', 'label': 'Expired'},
    {'code': 'EXTERNALLY_OBTAINED', 'label': 'Externally Obtained'},
    {'code': 'LENDER_CHECK_IN', 'label': 'Lender check in'},
    {'code': 'LOCAL_HOLDING', 'label': 'Local holding'},
    {'code': 'LOCATE_FAILED', 'label': 'Locate failed'},
    {'code': 'LOCATE_IN_PROCESS', 'label': 'Locate in process'},
    {'code': 'LOST_AND_FEE_PAID', 'label': 'Lost and fee paid'},
    {'code': 'LOST_COMMUNICATED', 'label': 'Lost communicated'},
    {'code': 'MANUAL_RENEW', 'label': 'Manual renew'},
    {'code': 'MEDIATED_RENEWAL', 'label': 'Mediated Patron Renewal'},
    {'code': 'OVERDUE_ITEM', 'label': 'Overdue request'},
    {'code': 'PENDING_APPROVAL', 'label': 'Pending Approval'},
    {'code': 'REACTIVATED', 'label': 'Reactivated'},
    {'code': 'READY_TO_SEND', 'label': 'Ready to be sent'},
    {'code': 'RECALLED_BOR', 'label': 'Recalled by partner'},
    {'code': 'REJECT', 'label': 'Reject'},
    {'code': 'RENEW_NOT_ACCEPTED', 'label': 'Renew request not accepted'},
    {'code': 'RENEW_REQUESTED', 'label': 'Renew requested'},
    {'code': 'RENEWED', 'label': 'Renewed by partner'},
    {'code': 'DAMAGED', 'label': 'Reported damaged item to partner'},
    {'code': 'REPORT_LOST', 'label': 'Reported lost item to partner'},
    {'code': 'REQUEST_ACCEPTED', 'label': 'Request accepted'},
    {'code': 'REQUEST_SENT', 'label': 'Request sent to partner'},
    {'code': 'RETURNED_TO_PARTNER', 'label': 'Returned item to partner'},
    {'code': 'SHIPPED_DIGITALLY', 'label': 'Shipped Digitally'},
    {'code': 'SHIPPED_PHYSICALLY', 'label': 'Shipped Physically'},
    {'code': 'CANCEL_REPLY', 'label': 'Waiting for cancel response'},
    {'code': 'RECEIVE_DIGITALLY_REPLY', 'label': 'Waiting for receive digitally'},
    {'code': 'WILL_SUPPLY', 'label': 'Will supply'}
]
